### ISSUE TITLE
Question about project

### ISSUE THREAD

**Issue by nicklasb** [myplanet/angular-action#9]
Hi, 
I am considering starting a project that implements action list functionality for AngularJS.
Problem is that I don't know if this project is already doing that, wouldn't want to reinvent any wheels for no reason. 
But I cannot find any documentation about this project anywhere, and honestly, I don't have time to figure it out by looking at the code.

I have written a document that outlines my ideas: https://github.com/OptimalBPM/angular-actions

Is that something similar to this project or its goals?

**Comment by atesgoral** [comment]
The aim of angular-action seems to be very different then the UI action paradigm your project addresses. angular-action is about a generic invoke/collect data/perform action paradigm that can be applied to forms and other things. So, you should have no worries about reinventing any wheels. But we, on the other hand, should be worried about our lack of documentation :)

**Comment by nicklasb** [comment]
Aha, then I think I understand. Well, there you have the documentation, you're done! :-)

I have sort of the opposite problem, my project lack any actual code. :-)

Good luck!
